### ISSUE TITLE
"cpm install" based on package.json

### ISSUE THREAD

**Issue by jzaefferer** [kriszyp/cpm#10]
Are there plans to add a install command that reads a package.json ala npm?

**Comment by kriszyp** [comment]
It does read the package.json (to determine the dependencies and install them and to find the "main" script so as to create a top level redirect module to point to it). Is there a particular part of the package.json that you want observed?

**Comment by jzaefferer** [comment]
So far I didn't actually try it, was just reading docs, and hijacking issues to poke some questions at the author. Thanks for clarifying that, though would be a good idea to mention that support in the readme as well.
