### ISSUE TITLE
Update package

### ISSUE THREAD

**Issue by arian** [kriszyp/cpm#8]
Hey,

I tried to update my just submitted package 'Complex' by resubmitting it. 
I made a small copy-paste error (wrong git repo) which caused some troubles so `cpm install Complex` fails..

Any idea how to fix it?

**Comment by kriszyp** [comment]
I deleted it for you, so you can resubmit it. Just FYI, for now you can
actually delete packages yourself by just doing an HTTP DELETE
http://packages.dojofoundation.org/Complex (no restrictions on that yet).
Kris

**Comment by arian** [comment]
Thanks, I've got it working now.

Another issue I had is that I used `git://github.com/arian/Complex.git` for the repositories key in the package.json (like the example at http://wiki.commonjs.org/wiki/Packages/1.0) but that made it fail as well. Maybe i'm just doing it wrong, or is that specification out-dated?
